# Generated by Django 4.2 on 2025-05-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlesson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
