# Generated by Django 5.2.6 on 2025-09-22 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together=set(),
        ),
    ]
