# Generated by Django 5.2.6 on 2025-10-02 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlesson', '0002_alter_teacheravailability_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='duration_minutes',
            field=models.PositiveIntegerField(choices=[(30, '30 minutes'), (60, '60 minutes'), (90, '90 minutes'), (120, '120 minutes')], default=60),
        ),
        migrations.CreateModel(
            name='TeacherDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
