# Generated by Django 4.2 on 2025-05-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlesson', '0003_customuser_group_lesson_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='duration_minutes',
            field=models.PositiveIntegerField(choices=[(45, '45 minut'), (60, '60 minut')], default=60),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
