# Generated by Django 4.2 on 2025-05-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlesson', '0004_lessonrequest_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheravailability',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='group_lesson_base_price',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='group_price_per_additional_student',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lesson_price_45min',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lesson_price_60min',
        ),
        migrations.AddField(
            model_name='customuser',
            name='extra_student_group_minute_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='price_per_minute_group',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='price_per_minute_individual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='GroupLessonInvite',
        ),
        migrations.DeleteModel(
            name='TeacherAvailability',
        ),
    ]
