# Generated by Django 5.2.6 on 2025-10-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlesson', '0004_teacheravailabilityperiod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAvailability',
        ),
    ]
