# Generated by Django 4.2 on 2025-05-31 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlesson', '0005_remove_teacheravailability_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='recurring_discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Discount % for recurring lessons'),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='recurring_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='duration_minutes',
            field=models.PositiveIntegerField(choices=[(45, '45 minutes'), (60, '60 minutes')], default=60),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.DeleteModel(
            name='TeacherUnavailableSlot',
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together={('teacher', 'day')},
        ),
    ]
