# Generated by Django 4.2 on 2025-06-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlesson', '0007_remove_lessonrequest_is_recurring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='is_one_time',
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='repeat_weeks',
            field=models.PositiveIntegerField(default=1, help_text='Number of weekly lessons (1 = one-time)'),
        ),
    ]
