# Generated by Django 4.2 on 2025-06-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlesson', '0008_remove_lessonrequest_is_one_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='is_one_time',
            field=models.BooleanField(default=True),
        ),
    ]
