# Generated by Django 4.2 on 2025-07-13 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlesson', '0009_lessonrequest_is_one_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='extra_student_group_minute_price',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='price_per_minute_group',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='price_per_minute_individual',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='recurring_discount_percent',
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='duration_minutes',
            field=models.PositiveIntegerField(choices=[(30, '30 minutes'), (35, '35 minutes'), (40, '40 minutes'), (45, '45 minutes'), (55, '55 minutes'), (60, '60 minutes'), (75, '75 minutes'), (90, '90 minutes'), (120, '120 minutes')], default=60),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_minute_individual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_per_minute_group', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('extra_student_group_minute_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recurring_discount_percent', models.PositiveIntegerField(default=0, help_text='Discount % for recurring lessons')),
                ('subjects', models.ManyToManyField(blank=True, to='urlesson.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=100)),
                ('number_class', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
