# Generated by Django 4.2 on 2025-07-16 16:17

from django.db import migrations
import urlesson.models


class Migration(migrations.Migration):

    dependencies = [
        ('urlesson', '0010_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', urlesson.models.CustomUserManager()),
            ],
        ),
    ]
