# Generated by Django 5.2.6 on 2025-10-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='can_commute',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
    ]
